/**
 * Zentrale Icon-Registry (Lucide, ADR-0018). Ersetzt die plattformabhängigen
 * Standard-Emojis durch einheitliche, themefähige Linien-Icons (erben die
 * aktuelle Textfarbe via `currentColor`, ziehen also Light/Dark automatisch mit).
 *
 * Konvention: Komponenten importieren die benannten Icons hier ODER nutzen
 * `APP_ICONS[slug]` für Feature-Apps, damit Slug→Icon an EINER Stelle gepflegt
 * wird. Standardgröße: `h-5 w-5` (Nav/Buttons), `h-4 w-4` (inline).
 */
import {
  Baby,
  BookUser,
  Cake,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  Crown,
  Download,
  Globe,
  Home,
  Image as ImageIcon,
  KeyRound,
  LogOut,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MoreVertical,
  PartyPopper,
  Phone,
  Plus,
  RotateCcw,
  Shield,
  ShoppingCart,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  User,
  Users,
  X,
} from 'lucide-react'

export type { LucideIcon }

export {
  Baby,
  BookUser,
  Cake,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  Crown,
  Download,
  Globe,
  Home,
  ImageIcon,
  KeyRound,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreVertical,
  PartyPopper,
  Phone,
  Plus,
  RotateCcw,
  Shield,
  ShoppingCart,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  User,
  Users,
  X,
}

/** Feature-App-Slug → Icon. Einzige Quelle der Wahrheit für App-Icons. */
export const APP_ICONS: Record<string, LucideIcon> = {
  'shopping-list': ShoppingCart,
  todo: CheckSquare,
  calendar: Calendar,
  gallery: ImageIcon,
  contacts: BookUser,
}
